# ===============================================================
#  Resolv Demo Start Script
#  Generated by deploy-demo.ps1
# ===============================================================

$ErrorActionPreference = "Continue"
$repoRoot = Split-Path $MyInvocation.MyCommand.Path -Parent
$apiDir = Join-Path $repoRoot "apps\api"
$webDir = Join-Path $repoRoot "apps\web"

Write-Host ""
Write-Host "=====================================================" -ForegroundColor Cyan
Write-Host "  Starting Resolv Platform" -ForegroundColor Cyan
Write-Host "=====================================================" -ForegroundColor Cyan
Write-Host ""

# Kill existing processes on these ports
$ports = @(3001, 3000)
foreach ($port in $ports) {
  try {
    $connections = netstat -ano -p tcp 2>$null | Select-String ":$port\s+.*LISTENING"
    foreach ($conn in $connections) {
      $pid = ($conn -split '\s+' | Where-Object { $_ -match '^\d+$' } | Select-Object -Last 1)
      if ($pid) {
        Stop-Process -Id $pid -Force -ErrorAction SilentlyContinue
        Write-Host "  Killed process on port $port (PID $pid)" -ForegroundColor Gray
      }
    }
  } catch {}
}

# Start API
Write-Host ""
Write-Host "  Starting API server on port 3001..." -ForegroundColor Yellow
$apiProcess = Start-Process -FilePath "node" -ArgumentList "dist/index.js" -WorkingDirectory $apiDir -PassThru -WindowStyle Minimized
Start-Sleep -Seconds 3

# Start Web
Write-Host "  Starting Web server on port 3000..." -ForegroundColor Yellow
$webProcess = Start-Process -FilePath "npx" -ArgumentList "next start" -WorkingDirectory $webDir -PassThru -WindowStyle Minimized
Start-Sleep -Seconds 5

Write-Host ""
Write-Host "=====================================================" -ForegroundColor Green
Write-Host "  Resolv is ready!" -ForegroundColor Green
Write-Host "" -ForegroundColor Green
Write-Host "  Frontend:  http://localhost:3000" -ForegroundColor Cyan
Write-Host "  API:       http://localhost:3001" -ForegroundColor Cyan
Write-Host "  Health:    http://localhost:3001/api/health" -ForegroundColor Cyan
Write-Host "" -ForegroundColor Green
Write-Host "  Login with your admin account credentials." -ForegroundColor White
Write-Host "" -ForegroundColor Green
Write-Host "  Press any key to stop both servers..." -ForegroundColor Yellow
Write-Host "=====================================================" -ForegroundColor Green

$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")

Write-Host ""
Write-Host "  Stopping servers..." -ForegroundColor Yellow
if ($apiProcess -and -not $apiProcess.HasExited) { Stop-Process -Id $apiProcess.Id -Force -ErrorAction SilentlyContinue }
if ($webProcess -and -not $webProcess.HasExited) { Stop-Process -Id $webProcess.Id -Force -ErrorAction SilentlyContinue }

# Clean up ports
foreach ($port in $ports) {
  try {
    $connections = netstat -ano -p tcp 2>$null | Select-String ":$port\s+.*LISTENING"
    foreach ($conn in $connections) {
      $pid = ($conn -split '\s+' | Where-Object { $_ -match '^\d+$' } | Select-Object -Last 1)
      if ($pid) { Stop-Process -Id $pid -Force -ErrorAction SilentlyContinue }
    }
  } catch {}
}

Write-Host "  Servers stopped." -ForegroundColor Gray
