@echo off
setlocal enabledelayedexpansion
:: ===============================================================
::  Resolv Demo Start Script
::  Generated by deploy-demo.ps1 on 2026-06-04 10:32
::  Hardened with fallbacks for common failure modes
:: ===============================================================

cd /d "%~dp0"

echo.
echo =====================================================
echo   Starting Resolv Platform
echo =====================================================
echo.

:: ?? Kill existing processes ??
echo   Checking for existing servers...
for %%p in (3001 3000) do (
  for /f "tokens=5" %%a in ('netstat -ano -p tcp ^| findstr ":%%p .*LISTENING"') do (
    taskkill /f /pid %%a >nul 2>&1
  )
)
echo   [OK] Ports cleared

:: ?? Check PostgreSQL ??
echo.
echo   Checking PostgreSQL...
set PG_RUNNING=0
for /f "tokens=1" %%a in ('sc query postgresql-x64-16 2^>nul ^| findstr "RUNNING"') do set PG_RUNNING=1
for /f "tokens=1" %%a in ('sc query postgresql-x64-17 2^>nul ^| findstr "RUNNING"') do set PG_RUNNING=1
for /f "tokens=1" %%a in ('sc query postgresql-x64-15 2^>nul ^| findstr "RUNNING"') do set PG_RUNNING=1
if !PG_RUNNING! equ 0 (
  echo   [!] PostgreSQL service not detected as running.
  echo       Attempting to start it...
  sc start postgresql-x64-16 >nul 2>&1 || sc start postgresql-x64-17 >nul 2>&1 || (
    echo   [WARN] Could not auto-start PostgreSQL.
  )
)

:: ?? Install deps if missing ??
echo.
if not exist "node_modules" (
  echo   Installing root dependencies...
  call npm install --loglevel=error 2>&1
  if !errorlevel! neq 0 (
    echo   Retrying with --legacy-peer-deps...
    call npm install --loglevel=error --legacy-peer-deps 2>&1
  )
  if !errorlevel! neq 0 (
    echo   [FAIL] npm install failed. Try: npm install --legacy-peer-deps
    pause
    exit /b 1
  )
  echo   [OK] Dependencies installed
) else (
  echo   [OK] node_modules found
)

:: ?? Workspace deps ??
for %%w in (apps\api apps\web) do (
  if not exist "%%w\node_modules" (
    echo   Installing %%w dependencies...
    pushd %%w
    call npm install --loglevel=error 2>&1
    popd
  )
)

:: ?? DB setup ??
echo.
echo   Setting up database...
if exist "apps\api\src\db\run_schema.js" (
  pushd apps\api
  node src\db\run_schema.js
  if !errorlevel! neq 0 ( echo   [WARN] Schema ) else ( echo   [OK] Schema )
  node src\db\run_seed.js
  if !errorlevel! neq 0 ( echo   [WARN] Seed ) else ( echo   [OK] Seed )
  node src\db\run_migration.js
  if !errorlevel! neq 0 ( echo   [WARN] Migrations ) else ( echo   [OK] Migrations )
  popd
) else (
  echo   [WARN] DB scripts not found. Skipping.
)

:: ?? Start servers ??
echo.
echo   Starting servers...
start "Resolv Dev" cmd /c "npm run dev"

:: Health check
echo   Waiting for servers...
for /l %%i in (1,1,30) do (
  >nul timeout /t 1 /nobreak
  >nul 2>&1 curl -s http://localhost:3001/api/health | findstr "api" && (
    echo   [OK] API ready
    goto :start_ready
  )
)
:start_ready

echo.
echo =====================================================
echo   Resolv is ready!
echo.
echo   Frontend:  http://localhost:3000
echo   API:       http://localhost:3001
echo   Health:    http://localhost:3001/api/health
echo.
echo   Default login:  marcus.johnson@company.com / password
echo                   20jenselucjj@gmail.com
echo.
echo   Press Enter to stop servers...
echo =====================================================
pause >nul

echo   Stopping...
for %%p in (3001 3000) do (
  for /f "tokens=5" %%a in ('netstat -ano -p tcp ^| findstr ":%%p .*LISTENING"') do (
    taskkill /f /pid %%a >nul 2>&1
  )
)
echo   Stopped.
