-- migrate_roles.sql ΓÇö Adds manager and readonly roles
-- Run: psql -d resolv -f migrate_roles.sql

-- Update users role CHECK constraint to include new roles
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;
ALTER TABLE users ADD CONSTRAINT users_role_check
  CHECK (role IN ('admin', 'manager', 'agent', 'user', 'readonly'));

-- Insert default role permissions for new roles
INSERT INTO system_settings (key, value, updated_at)
VALUES ('role_permissions', '[
  {"id":"admin","permissions":[{"key":"manage_users","enabled":true},{"key":"manage_settings","enabled":true},{"key":"manage_sla","enabled":true},{"key":"manage_categories","enabled":true},{"key":"delete_tickets","enabled":true},{"key":"view_audit_log","enabled":true},{"key":"manage_automation","enabled":true},{"key":"view_all_tickets","enabled":true},{"key":"assign_tickets","enabled":true},{"key":"manage_assets","enabled":true},{"key":"manage_asset_groups","enabled":true},{"key":"manage_email_templates","enabled":true},{"key":"manage_notification_settings","enabled":true},{"key":"manage_workflows","enabled":true},{"key":"manage_backup","enabled":true},{"key":"manage_ai_config","enabled":true},{"key":"manage_directory_sync","enabled":true},{"key":"manage_portal","enabled":true},{"key":"manage_agent_settings","enabled":true},{"key":"manage_reports","enabled":true},{"key":"manage_integrations","enabled":true}]},
  {"id":"manager","permissions":[{"key":"manage_users","enabled":true},{"key":"manage_settings","enabled":false},{"key":"manage_sla","enabled":true},{"key":"manage_categories","enabled":true},{"key":"delete_tickets","enabled":false},{"key":"view_audit_log","enabled":true},{"key":"manage_automation","enabled":true},{"key":"view_all_tickets","enabled":true},{"key":"assign_tickets","enabled":true},{"key":"manage_assets","enabled":true},{"key":"manage_asset_groups","enabled":true},{"key":"manage_email_templates","enabled":true},{"key":"manage_notification_settings","enabled":true},{"key":"manage_workflows","enabled":false},{"key":"manage_backup","enabled":false},{"key":"manage_ai_config","enabled":false},{"key":"manage_directory_sync","enabled":false},{"key":"manage_portal","enabled":true},{"key":"manage_agent_settings","enabled":true},{"key":"manage_reports","enabled":true},{"key":"manage_integrations","enabled":false}]},
  {"id":"agent","permissions":[{"key":"manage_users","enabled":false},{"key":"manage_settings","enabled":false},{"key":"manage_sla","enabled":false},{"key":"manage_categories","enabled":false},{"key":"delete_tickets","enabled":false},{"key":"view_audit_log","enabled":false},{"key":"manage_automation","enabled":false},{"key":"view_all_tickets","enabled":true},{"key":"assign_tickets","enabled":true},{"key":"manage_assets","enabled":true},{"key":"manage_asset_groups","enabled":false},{"key":"manage_email_templates","enabled":false},{"key":"manage_notification_settings","enabled":false},{"key":"manage_workflows","enabled":false},{"key":"manage_backup","enabled":false},{"key":"manage_ai_config","enabled":false},{"key":"manage_directory_sync","enabled":false},{"key":"manage_portal","enabled":false},{"key":"manage_agent_settings","enabled":false},{"key":"manage_reports","enabled":false},{"key":"manage_integrations","enabled":false}]},
  {"id":"user","permissions":[{"key":"manage_users","enabled":false},{"key":"manage_settings","enabled":false},{"key":"manage_sla","enabled":false},{"key":"manage_categories","enabled":false},{"key":"delete_tickets","enabled":false},{"key":"view_audit_log","enabled":false},{"key":"manage_automation","enabled":false},{"key":"view_all_tickets","enabled":false},{"key":"assign_tickets","enabled":false},{"key":"manage_assets","enabled":false},{"key":"manage_asset_groups","enabled":false},{"key":"manage_email_templates","enabled":false},{"key":"manage_notification_settings","enabled":false},{"key":"manage_workflows","enabled":false},{"key":"manage_backup","enabled":false},{"key":"manage_ai_config","enabled":false},{"key":"manage_directory_sync","enabled":false},{"key":"manage_portal","enabled":false},{"key":"manage_agent_settings","enabled":false},{"key":"manage_reports","enabled":false},{"key":"manage_integrations","enabled":false}]},
  {"id":"readonly","permissions":[{"key":"manage_users","enabled":false},{"key":"manage_settings","enabled":false},{"key":"manage_sla","enabled":false},{"key":"manage_categories","enabled":false},{"key":"delete_tickets","enabled":false},{"key":"view_audit_log","enabled":true},{"key":"manage_automation","enabled":false},{"key":"view_all_tickets","enabled":true},{"key":"assign_tickets","enabled":false},{"key":"manage_assets","enabled":false},{"key":"manage_asset_groups","enabled":false},{"key":"manage_email_templates","enabled":false},{"key":"manage_notification_settings","enabled":false},{"key":"manage_workflows","enabled":false},{"key":"manage_backup","enabled":false},{"key":"manage_ai_config","enabled":false},{"key":"manage_directory_sync","enabled":false},{"key":"manage_portal","enabled":false},{"key":"manage_agent_settings","enabled":false},{"key":"manage_reports","enabled":true},{"key":"manage_integrations","enabled":false}]}
]', NOW())
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
